<?php
namespace Database\Seeders;
use App\Models\GhanaDistrict;
use App\Models\GhanaRegion;
use Illuminate\Database\Seeder;
class GhanaAdministrativeSeeder extends Seeder
{
    public function run(): void
    {
        $regions = [
            ['name' => 'Ahafo', 'capital' => 'Goaso', 'districts' => [
                ['name' => 'Asunafo North', 'category' => 'Municipal', 'capital' => 'Goaso[a]'],
                ['name' => 'Asunafo South', 'category' => 'District', 'capital' => 'Kukuom'],
                ['name' => 'Asutifi North', 'category' => 'District', 'capital' => 'Kenyasi'],
                ['name' => 'Asutifi South', 'category' => 'District', 'capital' => 'Hwidiem'],
                ['name' => 'Tano North', 'category' => 'Municipal', 'capital' => 'Duayaw Nkwanta'],
                ['name' => 'Tano South', 'category' => 'Municipal', 'capital' => 'Bechem'],
            ]],
            ['name' => 'Ashanti', 'capital' => 'Kumasi', 'districts' => [
                ['name' => 'Adansi Asokwa', 'category' => 'District', 'capital' => 'Adansi Asokwa'],
                ['name' => 'Adansi North', 'category' => 'District', 'capital' => 'Fomena'],
                ['name' => 'Adansi South', 'category' => 'District', 'capital' => 'New Edubiase'],
                ['name' => 'Afigya-Kwabre North', 'category' => 'District', 'capital' => 'Boamang'],
                ['name' => 'Afigya-Kwabre South', 'category' => 'District', 'capital' => 'Kodie'],
                ['name' => 'Ahafo-Ano North', 'category' => 'Municipal', 'capital' => 'Tepa'],
                ['name' => 'Ahafo-Ano South East', 'category' => 'District', 'capital' => 'Adugyama'],
                ['name' => 'Ahafo-Ano South West', 'category' => 'District', 'capital' => 'Mankranso'],
                ['name' => 'Akrofuom', 'category' => 'District', 'capital' => 'Akrofuom'],
                ['name' => 'Amansie Central', 'category' => 'District', 'capital' => 'Jacobu'],
                ['name' => 'Amansie West', 'category' => 'District', 'capital' => 'Manso Nkwanta'],
                ['name' => 'Amansie South', 'category' => 'District', 'capital' => 'Manso Adubia'],
                ['name' => 'Asante-Akim Central', 'category' => 'Municipal', 'capital' => 'Konongo'],
                ['name' => 'Asante-Akim North', 'category' => 'District', 'capital' => 'Agogo'],
                ['name' => 'Asante-Akim South', 'category' => 'Municipal', 'capital' => 'Juaso'],
                ['name' => 'Asokore-Mampong', 'category' => 'Municipal', 'capital' => 'Asokore Mampong'],
                ['name' => 'Asokwa', 'category' => 'Municipal', 'capital' => 'Asokwa'],
                ['name' => 'Atwima-Kwanwoma', 'category' => 'District', 'capital' => 'Twedie'],
                ['name' => 'Atwima-Mponua', 'category' => 'District', 'capital' => 'Nyinahin'],
                ['name' => 'Atwima-Nwabiagya', 'category' => 'Municipal', 'capital' => 'Nkawie'],
                ['name' => 'Atwima-Nwabiagya North', 'category' => 'District', 'capital' => 'Barekese'],
                ['name' => 'Bekwai', 'category' => 'Municipal', 'capital' => 'Bekwai'],
                ['name' => 'Bosome Freho', 'category' => 'District', 'capital' => 'Asiwa'],
                ['name' => 'Bosomtwe', 'category' => 'District', 'capital' => 'Kuntanase'],
                ['name' => 'Ejisu', 'category' => 'Municipal', 'capital' => 'Ejisu'],
                ['name' => 'Ejura/Sekyedumase', 'category' => 'Municipal', 'capital' => 'Ejura'],
                ['name' => 'Juaben', 'category' => 'Municipal', 'capital' => 'Juaben'],
                ['name' => 'Kumasi', 'category' => 'Metropolitan', 'capital' => 'Kumasi[a]'],
                ['name' => 'Kwabre East', 'category' => 'Municipal', 'capital' => 'Mamponteng'],
                ['name' => 'Kwadaso', 'category' => 'Municipal', 'capital' => 'Kwadaso'],
                ['name' => 'Mampong', 'category' => 'Municipal', 'capital' => 'Mampong'],
                ['name' => 'Obuasi East', 'category' => 'Municipal', 'capital' => 'Tutuka'],
                ['name' => 'Obuasi', 'category' => 'Municipal', 'capital' => 'Obuasi'],
                ['name' => 'Offinso', 'category' => 'Municipal', 'capital' => 'Offinso'],
                ['name' => 'Offinso North', 'category' => 'District', 'capital' => 'Akomadan'],
                ['name' => 'Oforikrom', 'category' => 'Municipal', 'capital' => 'Oforikrom'],
                ['name' => 'Old Tafo', 'category' => 'Municipal', 'capital' => 'Old Tafo'],
                ['name' => 'Sekyere Afram Plains', 'category' => 'District', 'capital' => 'Drobonso'],
                ['name' => 'Sekyere Central', 'category' => 'District', 'capital' => 'Nsuta'],
                ['name' => 'Sekyere East', 'category' => 'District', 'capital' => 'Effiduase'],
                ['name' => 'Sekyere Kumawu', 'category' => 'District', 'capital' => 'Kumawu'],
                ['name' => 'Sekyere South', 'category' => 'District', 'capital' => 'Agona'],
                ['name' => 'Suame', 'category' => 'Municipal', 'capital' => 'Suame'],
            ]],
            ['name' => 'Bono', 'capital' => 'Sunyani', 'districts' => [
                ['name' => 'Banda', 'category' => 'District', 'capital' => 'Banda Ahenkro'],
                ['name' => 'Berekum East', 'category' => 'Municipal', 'capital' => 'Berekum'],
                ['name' => 'Berekum West', 'category' => 'District', 'capital' => 'Jinijini'],
                ['name' => 'Dormaa Central', 'category' => 'Municipal', 'capital' => 'Dormaa Ahenkro'],
                ['name' => 'Dormaa East', 'category' => 'District', 'capital' => 'Wamfie'],
                ['name' => 'Dormaa West', 'category' => 'District', 'capital' => 'Nkrankwanta'],
                ['name' => 'Jaman North', 'category' => 'District', 'capital' => 'Sampa'],
                ['name' => 'Jaman South', 'category' => 'Municipal', 'capital' => 'Drobo'],
                ['name' => 'Sunyani', 'category' => 'Municipal', 'capital' => 'Sunyani[a]'],
                ['name' => 'Sunyani West', 'category' => 'District', 'capital' => 'Odumase'],
                ['name' => 'Tain', 'category' => 'District', 'capital' => 'Nsawkaw'],
                ['name' => 'Wenchi', 'category' => 'Municipal', 'capital' => 'Wenchi'],
            ]],
            ['name' => 'Bono East', 'capital' => 'Techiman', 'districts' => [
                ['name' => 'Atebubu-Amantin', 'category' => 'Municipal', 'capital' => 'Atebubu'],
                ['name' => 'Kintampo North', 'category' => 'Municipal', 'capital' => 'Kintampo'],
                ['name' => 'Kintampo South', 'category' => 'District', 'capital' => 'Jema'],
                ['name' => 'Nkoranza North', 'category' => 'District', 'capital' => 'Busunya'],
                ['name' => 'Nkoranza South', 'category' => 'Municipal', 'capital' => 'Nkoranza'],
                ['name' => 'Pru East', 'category' => 'District', 'capital' => 'Yeji'],
                ['name' => 'Pru West', 'category' => 'District', 'capital' => 'Prang'],
                ['name' => 'Sene East', 'category' => 'District', 'capital' => 'Kajaji'],
                ['name' => 'Sene West', 'category' => 'District', 'capital' => 'Kwame Danso'],
                ['name' => 'Techiman', 'category' => 'Municipal', 'capital' => 'Techiman[a]'],
                ['name' => 'Techiman North', 'category' => 'District', 'capital' => 'Tuobodom'],
            ]],
            ['name' => 'Central', 'capital' => 'Cape Coast', 'districts' => [
                ['name' => 'Abura/Asebu/Kwamankese', 'category' => 'District', 'capital' => 'Abura-Dunkwa'],
                ['name' => 'Agona East', 'category' => 'District', 'capital' => 'Nsaba'],
                ['name' => 'Agona West Municipal', 'category' => 'Municipal', 'capital' => 'Agona Swedru'],
                ['name' => 'Ajumako/Enyan/Essiam', 'category' => 'District', 'capital' => 'Ajumako'],
                ['name' => 'Asikuma Odoben Brakwa', 'category' => 'District', 'capital' => 'Breman Asikuma'],
                ['name' => 'Assin Central', 'category' => 'Municipal', 'capital' => 'Assin Foso'],
                ['name' => 'Assin North', 'category' => 'District', 'capital' => 'Assin Bereku'],
                ['name' => 'Assin South', 'category' => 'District', 'capital' => 'Nsuaem Kyekyewere'],
                ['name' => 'Awutu Senya East', 'category' => 'Municipal', 'capital' => 'Kasoa'],
                ['name' => 'Awutu Senya West', 'category' => 'District', 'capital' => 'Awutu Breku'],
                ['name' => 'Cape Coast', 'category' => 'Metropolitan', 'capital' => 'Cape Coast[a]'],
                ['name' => 'Effutu', 'category' => 'Municipal', 'capital' => 'Winneba'],
                ['name' => 'Ekumfi', 'category' => 'District', 'capital' => 'Esakyir'],
                ['name' => 'Gomoa East', 'category' => 'District', 'capital' => 'Potsin'],
                ['name' => 'Gomoa Central', 'category' => 'District', 'capital' => 'Afransi'],
                ['name' => 'Gomoa West', 'category' => 'District', 'capital' => 'Apam'],
                ['name' => 'Komenda/Edina/Eguafo/Abirem', 'category' => 'Municipal', 'capital' => 'Elmina'],
                ['name' => 'Mfantsiman', 'category' => 'Municipal', 'capital' => 'Saltpond'],
                ['name' => 'Twifo Atti Morkwa', 'category' => 'District', 'capital' => 'Twifo Praso'],
                ['name' => 'Twifo/Hemang/Lower Denkyira', 'category' => 'District', 'capital' => 'Hemang'],
                ['name' => 'Upper Denkyira East', 'category' => 'Municipal', 'capital' => 'Dunkwa-on-Offin'],
                ['name' => 'Upper Denkyira West', 'category' => 'District', 'capital' => 'Diaso'],
            ]],
            ['name' => 'Eastern', 'capital' => 'Koforidua', 'districts' => [
                ['name' => 'Abuakwa North', 'category' => 'Municipal', 'capital' => 'Kukurantumi'],
                ['name' => 'Abuakwa South', 'category' => 'Municipal', 'capital' => 'Kibi'],
                ['name' => 'Achiase', 'category' => 'District', 'capital' => 'Achiase'],
                ['name' => 'Akuapim North', 'category' => 'Municipal', 'capital' => 'Akropong'],
                ['name' => 'Akuapim South', 'category' => 'District', 'capital' => 'Aburi'],
                ['name' => 'Akyemansa', 'category' => 'District', 'capital' => 'Ofoase'],
                ['name' => 'Asene Manso Akroso', 'category' => 'District', 'capital' => 'Manso'],
                ['name' => 'Asuogyaman', 'category' => 'District', 'capital' => 'Atimpoku'],
                ['name' => 'Atiwa East', 'category' => 'District', 'capital' => 'Anyinam'],
                ['name' => 'Atiwa West', 'category' => 'District', 'capital' => 'Kwabeng'],
                ['name' => 'Ayensuano', 'category' => 'District', 'capital' => 'Coaltar'],
                ['name' => 'Birim Central', 'category' => 'Municipal', 'capital' => 'Akim Oda'],
                ['name' => 'Birim North', 'category' => 'District', 'capital' => 'New Abirem'],
                ['name' => 'Birim South', 'category' => 'District', 'capital' => 'Akim Swedru'],
                ['name' => 'Denkyembour', 'category' => 'District', 'capital' => 'Akwatia'],
                ['name' => 'Fanteakwa North', 'category' => 'District', 'capital' => 'Begoro'],
                ['name' => 'Fanteakwa South', 'category' => 'District', 'capital' => 'Osino'],
                ['name' => 'Kwaebibirem', 'category' => 'Municipal', 'capital' => 'Kade'],
                ['name' => 'Kwahu Afram Plains North', 'category' => 'District', 'capital' => 'Donkorkrom'],
                ['name' => 'Kwahu Afram Plains South', 'category' => 'District', 'capital' => 'Tease'],
                ['name' => 'Kwahu East', 'category' => 'District', 'capital' => 'Abetifi'],
                ['name' => 'Kwahu South', 'category' => 'District', 'capital' => 'Mpraeso'],
                ['name' => 'Kwahu West', 'category' => 'Municipal', 'capital' => 'Nkawkaw'],
                ['name' => 'Lower Manya Krobo', 'category' => 'Municipal', 'capital' => 'Krobo Odumase'],
                ['name' => 'New Juaben North', 'category' => 'Municipal', 'capital' => 'Effiduase'],
                ['name' => 'New Juaben South', 'category' => 'Municipal', 'capital' => 'Koforidua[a]'],
                ['name' => 'Nsawam Adoagyire', 'category' => 'Municipal', 'capital' => 'Nsawam'],
                ['name' => 'Okere', 'category' => 'District', 'capital' => 'Adukrom'],
                ['name' => 'Suhum', 'category' => 'Municipal', 'capital' => 'Suhum, Ghana'],
                ['name' => 'Upper Manya Krobo', 'category' => 'District', 'capital' => 'Asesewa'],
                ['name' => 'Upper West Akim', 'category' => 'District', 'capital' => 'Adeiso'],
                ['name' => 'West Akim', 'category' => 'Municipal', 'capital' => 'Asamankese'],
                ['name' => 'Yilo-Krobo', 'category' => 'Municipal', 'capital' => 'Somanya'],
            ]],
            ['name' => 'Greater Accra', 'capital' => 'Accra', 'districts' => [
                ['name' => 'Ablekuma Central', 'category' => 'Municipal', 'capital' => 'Lartebiokorshie'],
                ['name' => 'Ablekuma North', 'category' => 'Municipal', 'capital' => 'Darkuman'],
                ['name' => 'Ablekuma West', 'category' => 'Municipal', 'capital' => 'Dansoman'],
                ['name' => 'Accra', 'category' => 'Metropolitan', 'capital' => 'Accra[a]'],
                ['name' => 'Ada East', 'category' => 'District', 'capital' => 'Ada Foah'],
                ['name' => 'Ada West', 'category' => 'District', 'capital' => 'Sege'],
                ['name' => 'Adenta', 'category' => 'Municipal', 'capital' => 'Adenta'],
                ['name' => 'Ashaiman', 'category' => 'Municipal', 'capital' => 'Ashaiman'],
                ['name' => 'Ayawaso Central', 'category' => 'Municipal', 'capital' => 'Kokomlemle'],
                ['name' => 'Ayawaso East', 'category' => 'Municipal', 'capital' => 'Nima'],
                ['name' => 'Ayawaso North', 'category' => 'Municipal', 'capital' => 'Accra New Town'],
                ['name' => 'Ayawaso West', 'category' => 'Municipal', 'capital' => 'Dzorwulu'],
                ['name' => 'Ga Central', 'category' => 'Municipal', 'capital' => 'Sowutuom'],
                ['name' => 'Ga East', 'category' => 'Municipal', 'capital' => 'Abokobi'],
                ['name' => 'Ga North', 'category' => 'Municipal', 'capital' => 'Amomole'],
                ['name' => 'Ga South', 'category' => 'Municipal', 'capital' => 'Ngleshie Amanfro'],
                ['name' => 'Ga West', 'category' => 'Municipal', 'capital' => 'Amasaman'],
                ['name' => 'Korle-Klottey', 'category' => 'Municipal', 'capital' => 'Osu'],
                ['name' => 'Kpone-Katamanso', 'category' => 'Municipal', 'capital' => 'Kpone'],
                ['name' => 'Krowor', 'category' => 'Municipal', 'capital' => 'Nungua'],
                ['name' => 'La-Dade-Kotopon', 'category' => 'Municipal', 'capital' => 'La'],
                ['name' => 'La-Nkwantanang-Madina', 'category' => 'Municipal', 'capital' => 'Madina'],
                ['name' => 'Ledzokuku', 'category' => 'Municipal', 'capital' => 'Teshie'],
                ['name' => 'Ningo-Prampram', 'category' => 'District', 'capital' => 'Prampram'],
                ['name' => 'Okaikwei North', 'category' => 'Municipal', 'capital' => 'Tesano'],
                ['name' => 'Shai-Osudoku', 'category' => 'District', 'capital' => 'Dodowa'],
                ['name' => 'Tema Metropolitan', 'category' => 'Metropolitan', 'capital' => 'Tema'],
                ['name' => 'Tema West', 'category' => 'Municipal', 'capital' => 'Tema Community 18'],
                ['name' => 'Weija Gbawe', 'category' => 'Municipal', 'capital' => 'Weija'],
            ]],
            ['name' => 'Northern', 'capital' => 'Tamale', 'districts' => [
                ['name' => 'Gushegu Municipal', 'category' => 'Municipal', 'capital' => 'Gushegu'],
                ['name' => 'Karaga', 'category' => 'District', 'capital' => 'Karaga'],
                ['name' => 'Kpandai', 'category' => 'District', 'capital' => 'Kpandai'],
                ['name' => 'Kumbungu', 'category' => 'District', 'capital' => 'Kumbungu'],
                ['name' => 'Mion', 'category' => 'District', 'capital' => 'Sang'],
                ['name' => 'Nanton', 'category' => 'District', 'capital' => 'Nanton'],
                ['name' => 'Nanumba North Municipal', 'category' => 'Municipal', 'capital' => 'Bimbilla'],
                ['name' => 'Nanumba South', 'category' => 'District', 'capital' => 'Wulensi'],
                ['name' => 'Saboba', 'category' => 'District', 'capital' => 'Saboba'],
                ['name' => 'Sagnarigu Municipal', 'category' => 'Municipal', 'capital' => 'Sagnarigu'],
                ['name' => 'Savelugu Municipal', 'category' => 'Municipal', 'capital' => 'Savelugu'],
                ['name' => 'Tamale Metropolitan', 'category' => 'Metropolitan', 'capital' => 'Tamale[a]'],
                ['name' => 'Tatale Sanguli', 'category' => 'District', 'capital' => 'Tatale'],
                ['name' => 'Tolon', 'category' => 'District', 'capital' => 'Tolon'],
                ['name' => 'Yendi Municipal', 'category' => 'Municipal', 'capital' => 'Yendi'],
                ['name' => 'Zabzugu', 'category' => 'District', 'capital' => 'Zabzugu'],
            ]],
            ['name' => 'North East', 'capital' => 'Nalerigu', 'districts' => [
                ['name' => 'Bunkpurugu Nyankpanduri', 'category' => 'District', 'capital' => 'Bunkpurugu'],
                ['name' => 'Chereponi', 'category' => 'District', 'capital' => 'Chereponi'],
                ['name' => 'East Mamprusi', 'category' => 'Municipal', 'capital' => 'Nalerigu[a]'],
                ['name' => 'Mamprugu Moagduri', 'category' => 'District', 'capital' => 'Yagaba'],
                ['name' => 'West Mamprusi', 'category' => 'Municipal', 'capital' => 'Walewale'],
                ['name' => 'Yunyoo-Nasuan', 'category' => 'District', 'capital' => 'Yunyoo'],
            ]],
            ['name' => 'Oti', 'capital' => 'Dambai', 'districts' => [
                ['name' => 'Biakoye', 'category' => 'District', 'capital' => 'Nkonya Ahenkro'],
                ['name' => 'Guan', 'category' => 'District', 'capital' => 'Likpe-Mate'],
                ['name' => 'Jasikan', 'category' => 'Municipal', 'capital' => 'Jasikan'],
                ['name' => 'Kadjebi', 'category' => 'District', 'capital' => 'Kadjebi'],
                ['name' => 'Krachi East', 'category' => 'Municipal', 'capital' => 'Dambai[a]'],
                ['name' => 'Krachi Nchumuru', 'category' => 'District', 'capital' => 'Chinderi'],
                ['name' => 'Krachi West', 'category' => 'Municipal', 'capital' => 'Kete Krachi'],
                ['name' => 'Nkwanta North', 'category' => 'District', 'capital' => 'Kpassa'],
                ['name' => 'Nkwanta South', 'category' => 'Municipal', 'capital' => 'Nkwanta'],
            ]],
            ['name' => 'Savannah', 'capital' => 'Damongo', 'districts' => [
                ['name' => 'Bole', 'category' => 'District', 'capital' => 'Bole'],
                ['name' => 'Central Gonja', 'category' => 'District', 'capital' => 'Buipe'],
                ['name' => 'East Gonja Municipal', 'category' => 'Municipal', 'capital' => 'Salaga'],
                ['name' => 'North Gonja', 'category' => 'District', 'capital' => 'Daboya'],
                ['name' => 'North East Gonja', 'category' => 'District', 'capital' => 'Kpalbe'],
                ['name' => 'Sawla-Tuna-Kalba', 'category' => 'District', 'capital' => 'Sawla'],
                ['name' => 'West Gonja', 'category' => 'Municipal', 'capital' => 'Damongo[a]'],
            ]],
            ['name' => 'Upper East', 'capital' => 'Bolgatanga', 'districts' => [
                ['name' => 'Bawku Municipal', 'category' => 'Municipal', 'capital' => 'Bawku'],
                ['name' => 'Bawku West', 'category' => 'District', 'capital' => 'Zebilla'],
                ['name' => 'Binduri', 'category' => 'District', 'capital' => 'Binduri'],
                ['name' => 'Bolgatanga East', 'category' => 'District', 'capital' => 'Zuarungu'],
                ['name' => 'Bolgatanga Municipal', 'category' => 'Municipal', 'capital' => 'Bolgatanga[a]'],
                ['name' => 'Bongo', 'category' => 'District', 'capital' => 'Bongo'],
                ['name' => 'Builsa North Municipal', 'category' => 'Municipal', 'capital' => 'Sandema'],
                ['name' => 'Builsa South', 'category' => 'District', 'capital' => 'Fumbisi'],
                ['name' => 'Garu', 'category' => 'District', 'capital' => 'Garu'],
                ['name' => 'Kassena-Nankana Municipal', 'category' => 'Municipal', 'capital' => 'Navrongo'],
                ['name' => 'Kassena-Nankana West', 'category' => 'District', 'capital' => 'Paga'],
                ['name' => 'Nabdam', 'category' => 'District', 'capital' => 'Nangodi'],
                ['name' => 'Pusiga', 'category' => 'District', 'capital' => 'Pusiga'],
                ['name' => 'Talensi', 'category' => 'District', 'capital' => 'Tongo'],
                ['name' => 'Tempane', 'category' => 'District', 'capital' => 'Tempane'],
            ]],
            ['name' => 'Upper West', 'capital' => 'Wa', 'districts' => [
                ['name' => 'Daffiama Bussie Issa', 'category' => 'District', 'capital' => 'Issa'],
                ['name' => 'Jirapa Municipal', 'category' => 'Municipal', 'capital' => 'Jirapa'],
                ['name' => 'Lambussie Karni', 'category' => 'District', 'capital' => 'Lambussie'],
                ['name' => 'Lawra Municipal', 'category' => 'Municipal', 'capital' => 'Lawra'],
                ['name' => 'Nadowli-Kaleo', 'category' => 'District', 'capital' => 'Nadowli'],
                ['name' => 'Nandom Municipal', 'category' => 'Municipal', 'capital' => 'Nandom'],
                ['name' => 'Sissala East Municipal', 'category' => 'Municipal', 'capital' => 'Tumu'],
                ['name' => 'Sissala West', 'category' => 'District', 'capital' => 'Gwollu'],
                ['name' => 'Wa East', 'category' => 'District', 'capital' => 'Funsi'],
                ['name' => 'Wa Municipal', 'category' => 'Municipal', 'capital' => 'Wa[a]'],
                ['name' => 'Wa West', 'category' => 'District', 'capital' => 'Wechiau'],
            ]],
            ['name' => 'Volta', 'capital' => 'Ho', 'districts' => [
                ['name' => 'Adaklu District', 'category' => 'District', 'capital' => 'Adaklu Waya'],
                ['name' => 'Afadzato South', 'category' => 'District', 'capital' => 'Ve Golokwati'],
                ['name' => 'Agotime Ziope', 'category' => 'District', 'capital' => 'Kpetoe'],
                ['name' => 'Akatsi North', 'category' => 'District', 'capital' => 'Ave-Dakpa'],
                ['name' => 'Akatsi South', 'category' => 'District', 'capital' => 'Akatsi'],
                ['name' => 'Anloga', 'category' => 'District', 'capital' => 'Anloga'],
                ['name' => 'Central Tongu', 'category' => 'District', 'capital' => 'Adidome'],
                ['name' => 'Ho Municipal', 'category' => 'Municipal', 'capital' => 'Ho[a]'],
                ['name' => 'Ho West', 'category' => 'District', 'capital' => 'Dzolokpuita'],
                ['name' => 'Hohoe Municipal', 'category' => 'Municipal', 'capital' => 'Hohoe'],
                ['name' => 'Keta Municipal', 'category' => 'Municipal', 'capital' => 'Keta'],
                ['name' => 'Ketu North Municipal', 'category' => 'Municipal', 'capital' => 'Dzodze'],
                ['name' => 'Ketu South Municipal', 'category' => 'Municipal', 'capital' => 'Denu'],
                ['name' => 'Kpando Municipal', 'category' => 'Municipal', 'capital' => 'Kpando'],
                ['name' => 'North Dayi', 'category' => 'District', 'capital' => 'Anfoega'],
                ['name' => 'North Tongu', 'category' => 'District', 'capital' => 'Battor Dugame'],
                ['name' => 'South Dayi', 'category' => 'District', 'capital' => 'Kpeve'],
                ['name' => 'South Tongu', 'category' => 'District', 'capital' => 'Sogakope'],
            ]],
            ['name' => 'Western', 'capital' => 'Sekondi-Takoradi', 'districts' => [
                ['name' => 'Ahanta West', 'category' => 'Municipal', 'capital' => 'Agona Ahanta'],
                ['name' => 'Amenfi Central', 'category' => 'District', 'capital' => 'Manso Amenfi'],
                ['name' => 'Amenfi West', 'category' => 'Municipal', 'capital' => 'Asankragua'],
                ['name' => 'Effia Kwesimintsim Municipal', 'category' => 'Municipal', 'capital' => 'Kwesimintsim'],
                ['name' => 'Ellembelle', 'category' => 'District', 'capital' => 'Nkroful'],
                ['name' => 'Jomoro', 'category' => 'Municipal', 'capital' => 'Half Assini'],
                ['name' => 'Mpohor', 'category' => 'District', 'capital' => 'Mpohor'],
                ['name' => 'Nzema East Municipal', 'category' => 'Municipal', 'capital' => 'Axim'],
                ['name' => 'Prestea-Huni Valley Municipal', 'category' => 'Municipal', 'capital' => 'Prestea'],
                ['name' => 'Sekondi Takoradi Metropolitan', 'category' => 'Metropolitan', 'capital' => 'Sekondi-Takoradi'],
                ['name' => 'Shama', 'category' => 'District', 'capital' => 'Shama'],
                ['name' => 'Tarkwa-Nsuaem Municipal', 'category' => 'Municipal', 'capital' => 'Tarkwa'],
                ['name' => 'Wassa Amenfi East', 'category' => 'Municipal', 'capital' => 'Wassa-Akropong'],
                ['name' => 'Wassa East', 'category' => 'District', 'capital' => 'Daboase'],
            ]],
            ['name' => 'Western North', 'capital' => 'Sefwi Wiawso', 'districts' => [
                ['name' => 'Aowin', 'category' => 'Municipal', 'capital' => 'Enchi'],
                ['name' => 'Bia East', 'category' => 'District', 'capital' => 'Sefwi Adabokrom'],
                ['name' => 'Bia West', 'category' => 'District', 'capital' => 'Essam-Debiso'],
                ['name' => 'Bibiani Anhwiaso Bekwai', 'category' => 'Municipal', 'capital' => 'Bibiani'],
                ['name' => 'Bodi', 'category' => 'District', 'capital' => 'Sefwi Bodi'],
                ['name' => 'Juaboso[130]', 'category' => 'District', 'capital' => 'Juaboso'],
                ['name' => 'Sefwi Akontombra[131]', 'category' => 'District', 'capital' => 'Sefwi Akontombra'],
                ['name' => 'Sefwi-Wiawso[132]', 'category' => 'Municipal', 'capital' => 'Sefwi Wiawso[a]'],
                ['name' => 'Suaman', 'category' => 'District', 'capital' => 'Dadieso'],
            ]],
        ];

        foreach ($regions as $regionData) {
            $region = GhanaRegion::updateOrCreate(
                ['name' => $regionData['name']],
                ['capital' => $regionData['capital']],
            );

            foreach ($regionData['districts'] as $districtData) {
                GhanaDistrict::updateOrCreate(
                    ['ghana_region_id' => $region->id, 'name' => $districtData['name']],
                    ['category' => $districtData['category'], 'capital' => $districtData['capital']],
                );
            }
        }
    }
}
